- name: Install Apache and MySQL

 hosts: apache:mysql

become: yes
tasks:
name: Install Apache
yum:
name: apache2
state: latest
when: apache in group_names"

name: Start Apache service
service:
name: apache2
state: started
enabled: yes
when: apache' in group_names"

name: Install MySQL
yum:
name: mysql-server state: latest
when:mysql' in group_names"

name: Start MySQL service

service:
name: mysql
state: started
enabled: yes when: 'mysql' in group_names"
